;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-paren
	c-electric-semi&comma
	electric-help-exit
	ivy-next-line
	ivy-switch-buffer
	thai-backward-kill-word
	thai-backward-word
	thai-forward-word
	thai-kill-word
	upcase-char
	))

(setq mc/cmds-to-run-once
      '(
	forward-symbol
	suspend-frame
	))
